interface Resources {
  common: {
    title: 'CSV Random Selector';
    description: 'This application allows you to upload a CSV file, select random records, and display the information of each record in a modal.';
    loaded_records: 'Loaded records: ';
    select_random_record: 'Select Random Record';
    no_more_records: 'No more records available.';
    btn_close: 'close';
    btn_upload: 'Drag and drop your CSV file here or click to upload.';
    btn_clean: 'Remove';
    btn_accept: 'Acept';
    pick_color: 'Pick a color';
  };
  index: {
    description: 'A client page, to demonstrate client side i18n';
    title: 'Client page';
    keywords: 'client, page, i18n';
  };
  login: {
    description: 'A client page, to demonstrate client side i18n';
    title: 'Client page';
    keywords: 'client, page, i18n';
    title_form: 'Login';
    user_form: 'Username';
    pass_form: 'Password';
    btn_form: 'Login';
    forget_pass: 'Forgot the password';
    error_user: 'Username is required';
    error_pass: 'Password is required';
    login_success: 'Login successful';
    error_login: 'Login failed';
  };
  layoutLogin: {
    description: 'A client page, to demonstrate client side i18n';
    title: 'Client page';
    keywords: 'client, page, i18n';
    sign_in: 'SIGN IN TO PLANIFIA';
    welcome_message: 'Welcome, We are glad to see you again!';
    copy_right: 'All Rights Reserved';
  };

  layoutResetPassword: {
    description: 'A client page, to demonstrate client side i18n';
    title: 'Reset Password page';
    keywords: 'client, page, i18n';
    header_message: 'Recupera tu cuenta';
    reset_password_message: 'Establece una nueva contraseña';
  };

  resetPassword: {
    title: 'Reset Password';
    description: 'A client page, to demonstrate client side i18n';
    keywords: 'client, page, i18n';
    title_form: 'Reset Your Password';
    new_pass_form: 'New Password';
    confirm_pass_form: 'Confirm Password';
    btn_form: 'Reset Password';
    btn_back_login: 'Back to login';
    message_password: "Make sure it's at least 20 characters OR at least 8 characters";
    message_succes: 'Password reset successfully!, please go back to login';
    error_pass: 'Please, enter your new password';
    error_pass_min: 'The password must be at least 6 characters long';
    error_confirm_pass: 'Please confirm your password';
    error_pass_match: 'Passwords do not match';
    error_reset: 'Error resetting password';
    error_pass_already_reset: 'Password reset already done';
    reset_success: 'Password reset successfully!';
    check_email_message: 'Please check your email for a link to reset your password';
    error_invalid_token: 'Invalid token';
  };

  requestResetPassword: {
    title: 'Request Password Reset';
    description: 'A client page to demonstrate client-side i18n';
    keywords: 'reset, password, request';
    title_form: 'Request Password Reset';
    email_form: "Enter your user account's verified email address";
    btn_form: 'Send Email';
    close: 'Close';
    btn_back_login: 'Back to login';
    error_invalid_email: 'Please enter a valid email address';
    error_email_required: 'The email is required';
    error_reset_request: 'Error sending password reset request';
    error_email_not_found: 'User login with this email not found';
    email_sent: "Email sent, please see your email and follow the instructions, if you don't see the email, please check your spam folder";
    reset_request_success: 'Password reset request sent successfully!';
  };

  sites: {
    layout_title_list: 'List Sites';
    layout_title_manage: 'Manage Sites';
    all: 'All';
    all_status:"Select Status"
    create: 'Create';
    not_results: 'No results found';
    filter_by_name: 'Filter name...';
    filter_by_status: 'Filter by status';
    filter_by_createdAt: 'Filter by date';
    error_fetching_sites: 'Error fetching sites';
    new_site: 'New Site';
    message_create_site: "Fill out the following form to create a new site. Click 'Create' when you're done.";
    name: "Name";
    description: "Description";
    primaryColor: "Primary Color";
    secondaryColor: "Secondary Color";
    template: "Template Color";
    logo: "Logo";
    status: "Status";
    createdAt: "Created At";
    updatedAt: "Updated At";
    ph_name: "Enter site name";
    ph_description: "Enter site description";
    ph_primaryColor: "Enter primary color";
    ph_secondaryColor: "Enter secondary color";
    ph_logo: "Enter file image";
    ph_template: "Select template color";
    purple_white: "Purple and White";
    blue_white: "Blue and White";
    active: "Active";
    inactive: "Inactive";
    btn_create: "Create";
    error_name: "Name is required";
    error_status: "Status is required";
    error_name_spaces: "Name cannot contain spaces";
    invalid_url: "Invalid URL";
    site_created: "Site created";
    select_status: "Select a status";
    actions: "Actions";
    site_updated: "Site updated";
    update_site: "Update Site";
    update_site_description: "Update the site information";
    update: "Update";
    change_status_description: "Are you sure you want to change the status of the site?";
    desactivate_site: "Desactivate Site";
    desactivate: "Desactivate";
    activate: "Activate";
    activate_site: "Activate Site";
    error_invalid_file_type: "The image must be in JPEG or PNG format";
    error_file_too_large: "The image must be less than 2MB";
    filter: "Filter"
  };

  exports: {
    export: "Export";
    export_to_pdf: "Export to PDF";
    export_to_excel: "Export to Excel";
    no_data_to_export: "No data to export";
  };

  dashboardIcons: {
    settings: 'Icon Settings';
    notifications: 'Icon Notifications';
    search: 'Icon Search';
    language: 'Icon Language';
    profile: 'Icon Profile';
    es: "Spanish";
    en: "English";
  };

  dashboardDirection: {
    dashboard: 'Dashboard';
    home: 'Home';
    users: 'User';
    dates: 'Dates';
    settings: 'Settings';
    clients: 'Clients';
    schedule: 'Schedule';
    dates: 'Dates';
    create: 'Create';
    create_user: 'Create User';
    view_schedule: 'View Schedule';
    add_appointment: 'Add Appointment';
    manage_clients: 'Manage Clients';
    clients_list: 'Client List';
    system_users: 'System Users';
    manage_users: 'Manage Users';
    users_list: 'User List';
    reports: 'Reports';
    client_report: 'Client Report';
    appointment_report: 'Appointment Report';
    administration: 'Administration';
    profile: 'Profile';
    change_password: 'Change Password';
    email_templates: 'Email Templates';
    whatsapp_templates: 'Whatsapp Templates';
    business_data: 'Business Data';
    sites: 'Sites';
    manage_sites: 'Manage Sites';
    sites_list: 'Site List';
    files: 'Files';
    generate_files: "Generate File";
    assign_files: "Assign File";
    generate: "Generate";
    list: 'List';
    add: 'Add';
    password: 'Password';
    email: 'Email';
    whatsapp: 'Whatsapp';
    business: 'Business';
    manage: 'Manage';
    view: 'View';
    appointments: 'Appointments';
    admin_template:'Admin template';
    admin_profile: 'Profile';
  };

  clients: {
    manage: 'Manage Clients';
    list: 'Clients List';
    report: 'Clients Report';
    clients_list: 'Client List';
    new_client: 'New Client';
    new_client_description: 'Create a new client';
    client_created: 'Client created';
    client_updated: 'Client updated';
    update_client: 'Update Client';
    update_client_description: 'Update the client information';
    update: 'Update';
    create: 'Create';
    cancel: 'Cancel';
    client: 'Client';
    edit: 'Edit';
    delete: 'Delete';
    username: 'Username';
    name: 'Name';
    lastName: 'Last Name';
    email: 'Email';
    document: 'Document';
    phone: 'Phone';
    direction: 'Direction';
    countryId: 'Country';
    provinceId: 'Province';
    cantonId: 'Canton';
    parish: 'Parish';
    createdAt: 'Creation Date';
    updateAt: 'Update Date';
    actions: 'Actions';
    error_username: 'Username is required';
    error_name: 'Name is required';
    error_last_name: 'Last name is required';
    error_province: 'Province is required';
    error_canton: 'Canton is required';
    error_email: 'Email is required';
    error_document: 'Document is required';
    error_phone: 'Phone is required';
    error_direction: 'Direction is required';
    invalid_email: 'Invalid email';
    rows_per_page: 'Rows per page';
    show_rows: 'Show rows';
    page: 'Page';
    of: 'of';
    columns: 'Columns';
    country_name: 'Country Name';
    province_name: 'Province Name';
    canton_name: 'Canton Name';
    hide: 'Hide';
    columns: 'Columns';
    no_data: 'No data';
    select_country: 'Select a country';
    select_province: 'Select a province';
    select_canton: 'Select a canton';
    filter_by_username: 'Filter by username';
    filter_by_name: 'Filter by name';
    filter_by_lastName: 'Filter by last name';
    filter_by_email: 'Filter by email';
    filter_by_document: 'Filter by document';
    filter_by_canton: 'Filter by canton';
    filter_by_createdAt: 'Filter by created date';
    filter_by_updatedAt: 'Filter by updated date';
    delete_sure: 'Are you absolutely sure?';
    search_canton: 'Search canton...';
    no_canton: 'No canton found';
    delete_message: 'This action cannot be undone. This could permanently delete the client.';
    no_items_available: "no_items_available";
    filter: "Filter";
  };

  dashboardLayout: {
    description: 'A client page, to demonstrate client side i18n';
    title: 'Client page';
    keywords: 'client, page, i18n';
  };

  users: {
    filter_by_createdAt: 'Filter by createdAt';
    delete_sure: 'Are you absolutely sure?';
    delete_message: 'This action cannot be undone. This could permanently delete the client.';
    cancel: 'Cancel';
    delete: 'Delete';
    username: 'Username';
    email: 'Email';
    status: 'Status';
    document: 'Document';
    role: 'Role';
    phone: 'Phone';
    direction: 'Direction';
    createdAt: 'Creation Date';
    updateAt: 'Update Date';
    actions: 'Actions';
    user_created: 'user_created';
    new_user: 'New user';
    new_user_description: 'New user description';
    create: 'Create';
    password_reset_success: 'Password reset success';
    reset_password: 'Reset password';
    reset_password_description: 'Reset password description';
    new_password: 'New password';
    password_required: 'Password required';
    confirm_password: 'Confirm password';
    passwords_do_not_match: 'Passwords do not match';
    accept: 'Accept';
    manage: 'Manage users';
    user_updated: 'User updated';
    update_user: 'Update user';
    update_user_description: 'Update user description';
    error_username: 'Error username';
    invalid_email: 'Invalid email';
    error_email: 'Error email';
    error_role: 'Error role';
    select_country: 'Select country';
    select_province: 'Select province';
    select_canton: 'Select canton';
    select_parish: 'Select parish';
    countryId: 'Country Id';
    provinceId: 'Province Id';
    cantonId: 'Canton Id';
    parishId: 'Parish Id';
    error_password_min: 'Error password min';
    error_password: 'Error password';
    password: 'Password';
    filter_by_username: 'Filter by username';
    filter_by_role: 'Filter by role';
    filter_by_status: 'Filter by status';
    filter: 'Filter';
    no_data: 'No data';
    update: 'Update';
    error_status: 'Status error';
    active: "Active";
    inactive: "Inactive";
    select_status: "Select status";
    select_role: "Select role";
    roles_super_admin: "Super Admin"
    roles_admin: "Admin";
    roles_assistant: "Assistant";
  };
  templates: {  
    templates: "Templates";
    admin_templates_email: "Admin templates email";
    manage_templates: "Manage templates";
    new_template: "New template";
    new_template_description: "Create a new template";
    template_created: "Template created successfully";
    template_updated: "Template updated successfully";
    delete_sure: "Are you sure you want to delete this template?";
    delete_message: "This action cannot be undone.",
    cancel: "Cancel";
    delete: "Delete";
    create: "Create";
    update: "Update";
    update_template: "Update template";
    update_template_description: "Modify the selected template";
    name: "Name";
    content: "Content";
    action: "Action";
    templateEnvIds: "Environment Variables";
    status: "Status";
    active: "Active";
    inactive: "Inactive";
    activate: "Activate";
    activate_true: "Activate";
    activate_false: "Deactivate";
    select_action: "Select action";
    select_template_envs: "Select environment variables";
    select_status: "Select status";
    filter_by_name: "Filter by name";
    filter_by_status: "Filter by status";
    filter_by_createdAt: "Filter by creation date";
    no_data: "No data";
    createdAt: "Creation date";
    error_name: "Name is required";
    error_content: "Content is required";
    error_status: "Status is required";
    error_activate: "Activate field is required";
    actions: "Actions";
    select_activate: "select activate"
    add_to_content: "add to content";
    select_base_template: "Select base template"
    error_template_env_ids: "Error template env ids"
    select_variable:"Select variable";
    error_missing_variables:"Error missing variables";
    activated: "Activate";
    deactivated: "Desactive";
    error_variable_mismatch: "Error variable mismatch";
    filter:"Filter"
  };
  files: {
    generate_files: string;
    assign_files: string;
    form_title: string;
    form_description: string;
    form_title_placeholder: string;
    form_description_placeholder: string;
    back_to_list: string;
    question: string;
    option_1: string;
    option_2: string;
    add_section: string;
    filter_by_createdAt : string;
    section_title_placeholder: string;
    add_question: string;
    form_created: string;
    error_loading_form: string;
    section_title: string;
    question: string;
    create: string;
    form_updated: string;
    update: string;
    titles: {
      form_manager: string;
      recent_forms: string;
      form_preview: string;
    };
    question_type: {
      short_answer: string;
      number: string;
      email: string;
      dropdown: string;
      checkboxes: string;
      file_upload: string;
      date: string;
      section: string;
    };
    placeholder: {
      short_answer: string;
      number: string;
      email: string;
      option: string;
      question: string;
      date: string;
    };
    button: {
      add_option: string;
      remove: string;
      duplicate: string;
      save : string;
      create_form: string;
    };
    label: {
      required: string;
    };
    labels: {
      last_opened: string;
      preview: string;
      description: string;
    };
    messages: {
      no_recent_forms: string;
      no_preview_available: string;
      no_description: string;
      untitled_form: string;
      form_deleted: string;
      enter_new_title: string;
      title_updated: string;
      no_answer: string;
    };
    errors: {
      load_forms: string;
      delete_failed: string;
      update_failed: string;
      load_form: string;
    };
    actions: {
      edit_title: string;
      delete: string;
      open_in_new_tab: string;
    }
  };

  userDropdown: {
    profile: 'Profile';
    preferences: 'Preferences';
    logout: 'Logout';
    user: 'User';
    logout_confirmation: 'Are you sure you want to logout?';
    cancel: 'Cancel';
  };

  administration: {
    //profile components
    profile_updated: "Profile updated successfully";
    confirm_changes: "Confirm Changes";
    are_you_sure_to_update: "Are you sure you want to update?";
    save: "Save";
    cancel: "Cancel";
    accept: "Accept";
    updating: "Updating...";
    username: "Username";
    email: "Email";
    status: "Status";
    phone: "Phone";
    direction: "Address";
    country: "Country";
    province: "Province";
    canton: "Canton";
    parish: "Parish";
    select_status: "Select status";
    select_role: "Select role";
    select_country: "Select country";
    select_province: "Select province";
    select_canton: "Select canton";
    select_parish: "Select parish";
    active: "Active";
    inactive: "Inactive";
    roles_super_admin: "Super Administrator";
    roles_admin: "Administrator";
    roles_assistant: "Assistant";
    error_username: "Username is required";
    error_email: "Email is required";
    invalid_email: "Invalid email address";
    error_role: "Role is required";
    error_status: "Status is required";
    unexpected_error: "Unexpected error occurred";
    profile_of: "Profile of: ";
    role: "Role";
    no_changes: "No changes";
    change_password: "Change your password";
    click_here: "Click Here";
//password components
    password_current: "Current Password";
    password_new: "New Password";
    password_confirm: "Confirm New Password";
    password_current_required: "Current password is required";
    password_new_required: "New password is required";
    password_new_min: "New password must be at least 6 characters";
    password_confirm_required: "Confirmation of new password is required";
    password_confirm_mismatch: "Passwords do not match";
    password_change_button: "Change Password";
    password_changing: "Changing...";
    password_change_success: "Password changed successfully";
    password_change_error: "Error changing password";
    password_change_email_sent: "Password change email sent";
  };
}
export default Resources;
